version: "3.4"

services:

  # psql_prod_db:
  #   platform: linux/amd64
  #   container_name: psql_prod_db
  #   image: postgres
  #   ports:
  #     - 5434:5432
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - APP_NAME=psql_prod_db
  #     - TZ=Asia/Manila
  #     - DEBIAN_FRONTEND=noninteractive
  #   restart: always
      

  jpsc_prod_api:
    platform: linux/amd64
    container_name: jpsc_prod_api
    build: ./api
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker my_app.main:app -b 0.0.0.0:8001
    environment:
      - APP_NAME=jpsc_api
      - TZ=Asia/Manila
      - DEBIAN_FRONTEND=noninteractive
    depends_on:
      - psql_prod_db
    ports:
      - 82:8001
    expose:
      - 82
    restart: always

  # nginx:
  #   image: nginx:1.14.2-alpine
  #   # image: nginx:stable
  #   restart: always
  #   environment:
  #     - TZ=Asia/Manila
  #   volumes:
  #     - ./public_html:/public_html
  #     - ./conf.d:/etc/nginx/conf.d/
  #     - ./dhparam:/etc/nginx/dhparam
  #     - ./certbot/conf/:/etc/nginx/ssl/
  #     - ./certbot/data:/usr/share/nginx/html/letsencrypt
  #   ports:
  #     - 80:80
  #     - 443:443


  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email romel.catalogo@jpoonandsons.com --agree-tos --no-eff-email -d api-test.jpoonandsons.com
  #   volumes:
  #     - ./certbot/conf/:/etc/letsencrypt
  #     - ./certbot/logs/:/var/log/letsencrypt
  #     - ./certbot/data:/usr/share/nginx/html/letsencrypt

  
  