"""latest

Revision ID: 0d83fcdfd75b
Revises: 7cf4f0a5d1eb
Create Date: 2022-10-11 01:36:07.033029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '0d83fcdfd75b'
down_revision = '7cf4f0a5d1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_terms',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_payment_terms_code'), 'payment_terms', ['code'], unique=True)
    op.create_index(op.f('ix_payment_terms_description'), 'payment_terms', ['description'], unique=False)
    op.create_table('customer',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['location'], ['branch.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['payment_terms'], ['payment_terms.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_full_name'), 'customer', ['full_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_location'), 'customer', ['location'], unique=False)
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brgy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('other_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_address_brgy'), 'customer_address', ['brgy'], unique=False)
    op.create_index(op.f('ix_customer_address_city_municipality'), 'customer_address', ['city_municipality'], unique=False)
    op.create_index(op.f('ix_customer_address_customer_code'), 'customer_address', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customer_address_id'), 'customer_address', ['id'], unique=False)
    op.create_index(op.f('ix_customer_address_other_details'), 'customer_address', ['other_details'], unique=False)
    op.create_index(op.f('ix_customer_address_province'), 'customer_address', ['province'], unique=False)
    op.create_index(op.f('ix_customer_address_street_address'), 'customer_address', ['street_address'], unique=False)
    op.create_table('price_quotation_h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transdate', sa.DateTime(), nullable=True),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispatching_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('docstatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pq_status', sa.Integer(), nullable=True),
    sa.Column('sq_number', sa.Integer(), nullable=True),
    sa.Column('date_dispatched', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('otherfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('date_canceled', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('canceled_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['payment_terms'], ['payment_terms.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_id')
    )
    op.create_index(op.f('ix_price_quotation_h_customer_code'), 'price_quotation_h', ['customer_code'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_delivery_method'), 'price_quotation_h', ['delivery_method'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_dispatching_branch'), 'price_quotation_h', ['dispatching_branch'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_docstatus'), 'price_quotation_h', ['docstatus'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_id'), 'price_quotation_h', ['id'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_payment_terms'), 'price_quotation_h', ['payment_terms'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_pq_status'), 'price_quotation_h', ['pq_status'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_reference'), 'price_quotation_h', ['reference'], unique=True)
    op.create_index(op.f('ix_price_quotation_h_sq_number'), 'price_quotation_h', ['sq_number'], unique=False)
    op.create_table('price_quotation_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_attachment_doc_id'), 'price_quotation_attachment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_attachment_id'), 'price_quotation_attachment', ['id'], unique=False)
    op.create_table('price_quotation_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_comment_doc_id'), 'price_quotation_comment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_comment_id'), 'price_quotation_comment', ['id'], unique=False)
    op.create_table('price_quotation_r',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('srp_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('linetotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['uom.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_r_doc_id'), 'price_quotation_r', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_id'), 'price_quotation_r', ['id'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_item_code'), 'price_quotation_r', ['item_code'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_uom'), 'price_quotation_r', ['uom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_quotation_r_uom'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_item_code'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_id'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_doc_id'), table_name='price_quotation_r')
    op.drop_table('price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_comment_id'), table_name='price_quotation_comment')
    op.drop_index(op.f('ix_price_quotation_comment_doc_id'), table_name='price_quotation_comment')
    op.drop_table('price_quotation_comment')
    op.drop_index(op.f('ix_price_quotation_attachment_id'), table_name='price_quotation_attachment')
    op.drop_index(op.f('ix_price_quotation_attachment_doc_id'), table_name='price_quotation_attachment')
    op.drop_table('price_quotation_attachment')
    op.drop_index(op.f('ix_price_quotation_h_sq_number'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_reference'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_pq_status'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_payment_terms'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_id'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_docstatus'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_dispatching_branch'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_delivery_method'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_customer_code'), table_name='price_quotation_h')
    op.drop_table('price_quotation_h')
    op.drop_index(op.f('ix_customer_address_street_address'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_province'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_other_details'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_id'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_customer_code'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_city_municipality'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_brgy'), table_name='customer_address')
    op.drop_table('customer_address')
    op.drop_index(op.f('ix_customer_location'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_full_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_payment_terms_description'), table_name='payment_terms')
    op.drop_index(op.f('ix_payment_terms_code'), table_name='payment_terms')
    op.drop_table('payment_terms')
    # ### end Alembic commands ###
