"""latest:


Revision ID: 1417a75c359c
Revises: c0de6a221503
Create Date: 2022-10-26 21:17:13.587278

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '1417a75c359c'
down_revision = 'c0de6a221503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
