"""latest

Revision ID: 1cc759386aac
Revises: 93236d7f5799
Create Date: 2022-10-20 12:08:44.078083

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '1cc759386aac'
down_revision = '93236d7f5799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_group', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.create_index(op.f('ix_menu_group_is_active'), 'menu_group', ['is_active'], unique=False)
    op.add_column('object_type', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.create_index(op.f('ix_object_type_is_active'), 'object_type', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_type_is_active'), table_name='object_type')
    op.drop_column('object_type', 'is_active')
    op.drop_index(op.f('ix_menu_group_is_active'), table_name='menu_group')
    op.drop_column('menu_group', 'is_active')
    # ### end Alembic commands ###
