"""latest

Revision ID: 1f87bfef4ac8
Revises: a22fcfafe1c1
Create Date: 2022-09-15 03:14:33.338629

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '1f87bfef4ac8'
down_revision = 'a22fcfafe1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_h', 'reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_h', 'reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
