"""itemGroupuserAuth

Revision ID: 23537bb2c824
Revises: c29ca5f86a8b
Create Date: 2022-10-29 13:13:04.708318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '23537bb2c824'
down_revision = 'c29ca5f86a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_group_user_auth',
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('item_group_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_last_purc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('grant_avg_value', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('date_udpated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_group_code', 'updated_by')
    )
    op.create_index(op.f('ix_item_group_user_auth_item_group_code'), 'item_group_user_auth', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_item_group_user_auth_system_user_id'), 'item_group_user_auth', ['system_user_id'], unique=False)
    op.create_index(op.f('ix_item_group_user_auth_updated_by'), 'item_group_user_auth', ['updated_by'], unique=False)
    op.drop_column('item_group', 'is_allow_last_purch')
    op.drop_column('item_group', 'is_allow_avg_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_group', sa.Column('is_allow_avg_value', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('item_group', sa.Column('is_allow_last_purch', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_group_user_auth_updated_by'), table_name='item_group_user_auth')
    op.drop_index(op.f('ix_item_group_user_auth_system_user_id'), table_name='item_group_user_auth')
    op.drop_index(op.f('ix_item_group_user_auth_item_group_code'), table_name='item_group_user_auth')
    op.drop_table('item_group_user_auth')
    # ### end Alembic commands ###
