"""latest

Revision ID: 23fbb5a00c57
Revises: 2a42588ce481
Create Date: 2022-09-13 02:35:15.917602

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '23fbb5a00c57'
down_revision = '2a42588ce481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['location'], ['branch.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_location'), 'customer', ['location'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brgy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city_municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('other_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_customer_address_brgy'), 'customer_address', ['brgy'], unique=False)
    op.create_index(op.f('ix_customer_address_city_municipality'), 'customer_address', ['city_municipality'], unique=False)
    op.create_index(op.f('ix_customer_address_customer_code'), 'customer_address', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customer_address_street_address'), 'customer_address', ['street_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_address_street_address'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_customer_code'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_city_municipality'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_brgy'), table_name='customer_address')
    op.drop_table('customer_address')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_location'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
