"""pricelist

Revision ID: 2604e0e70def
Revises: b681e66703eb
Create Date: 2022-09-14 07:07:32.928739

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '2604e0e70def'
down_revision = 'b681e66703eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pricelist_r', 'pricelist_h', ['pricelist_code'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricelist_r', type_='foreignkey')
    # ### end Alembic commands ###
