"""customer

Revision ID: 2b036a575378
Revises: 9445258ccf9e
Create Date: 2022-09-24 03:07:42.746316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '2b036a575378'
down_revision = '9445258ccf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('payment_term', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('customer', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'customer', 'payment_term', ['payment_term'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'is_approved')
    op.drop_column('customer', 'payment_term')
    # ### end Alembic commands ###
