"""new_col_customer

Revision ID: 329fcefbc3fb
Revises: 438721df40c1
Create Date: 2022-11-09 20:16:01.173262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '329fcefbc3fb'
down_revision = '438721df40c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
