"""latest

Revision ID: 39cf4119dd2f
Revises: b76cc8589cbb
Create Date: 2022-10-17 09:30:16.945411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '39cf4119dd2f'
down_revision = 'b76cc8589cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('objtype', sa.Integer(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_auth'), 'authorization', ['auth'], unique=False)
    op.create_index(op.f('ix_authorization_id'), 'authorization', ['id'], unique=False)
    op.create_index(op.f('ix_authorization_objtype'), 'authorization', ['objtype'], unique=False)
    op.create_index(op.f('ix_authorization_system_user_id'), 'authorization', ['system_user_id'], unique=False)
    op.create_table('menu_group',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_menu_group_code'), 'menu_group', ['code'], unique=True)
    op.add_column('object_type', sa.Column('menu_group_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_object_type_menu_group_code'), 'object_type', ['menu_group_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_type_menu_group_code'), table_name='object_type')
    op.drop_column('object_type', 'menu_group_code')
    op.drop_index(op.f('ix_menu_group_code'), table_name='menu_group')
    op.drop_table('menu_group')
    op.drop_index(op.f('ix_authorization_system_user_id'), table_name='authorization')
    op.drop_index(op.f('ix_authorization_objtype'), table_name='authorization')
    op.drop_index(op.f('ix_authorization_id'), table_name='authorization')
    op.drop_index(op.f('ix_authorization_auth'), table_name='authorization')
    op.drop_table('authorization')
    # ### end Alembic commands ###
