"""latest

Revision ID: 50c9dc84b0a1
Revises: 6c0a88c79634
Create Date: 2022-10-22 03:42:51.985450

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50c9dc84b0a1'
down_revision = '6c0a88c79634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whseinv_id', table_name='whseinv')
    op.drop_index('ix_whseinv_item_code', table_name='whseinv')
    op.drop_index('ix_whseinv_whsecode', table_name='whseinv')
    op.drop_table('whseinv')
    op.drop_index('ix_inv_adj_out_h_hashed_id', table_name='inv_adj_out_h')
    op.drop_index('ix_inv_adj_out_h_id', table_name='inv_adj_out_h')
    op.drop_index('ix_inv_adj_out_h_objtype', table_name='inv_adj_out_h')
    op.drop_index('ix_inv_adj_out_h_reference', table_name='inv_adj_out_h')
    op.drop_table('inv_adj_out_h')
    op.drop_index('ix_inv_trfr_req_h_docstatus', table_name='inv_trfr_req_h')
    op.drop_index('ix_inv_trfr_req_h_hashed_id', table_name='inv_trfr_req_h')
    op.drop_index('ix_inv_trfr_req_h_id', table_name='inv_trfr_req_h')
    op.drop_index('ix_inv_trfr_req_h_objtype', table_name='inv_trfr_req_h')
    op.drop_index('ix_inv_trfr_req_h_reference', table_name='inv_trfr_req_h')
    op.drop_table('inv_trfr_req_h')
    op.drop_index('ix_inv_adj_in_h_hashed_id', table_name='inv_adj_in_h')
    op.drop_index('ix_inv_adj_in_h_id', table_name='inv_adj_in_h')
    op.drop_index('ix_inv_adj_in_h_objtype', table_name='inv_adj_in_h')
    op.drop_index('ix_inv_adj_in_h_reference', table_name='inv_adj_in_h')
    op.drop_table('inv_adj_in_h')
    op.drop_index('ix_inv_transaction_base_id', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_id', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_item_code', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_objtype', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_row_id', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_transdate', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_whsecode', table_name='inv_transaction')
    op.drop_index('ix_inv_transaction_whsecode2', table_name='inv_transaction')
    op.drop_table('inv_transaction')
    op.drop_index('ix_inv_receive_h_docstatus', table_name='inv_receive_h')
    op.drop_index('ix_inv_receive_h_id', table_name='inv_receive_h')
    op.drop_index('ix_inv_receive_h_objtype', table_name='inv_receive_h')
    op.drop_index('ix_inv_receive_h_reference', table_name='inv_receive_h')
    op.drop_table('inv_receive_h')
    op.drop_index('ix_inv_trfr_h_docstatus', table_name='inv_trfr_h')
    op.drop_index('ix_inv_trfr_h_id', table_name='inv_trfr_h')
    op.drop_index('ix_inv_trfr_h_objtype', table_name='inv_trfr_h')
    op.drop_index('ix_inv_trfr_h_reference', table_name='inv_trfr_h')
    op.drop_table('inv_trfr_h')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_trfr_h',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='inv_trfr_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_trfr_h_objtype_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='inv_trfr_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inv_trfr_h_pkey'),
    sa.UniqueConstraint('hashed_id', name='inv_trfr_h_hashed_id_key')
    )
    op.create_index('ix_inv_trfr_h_reference', 'inv_trfr_h', ['reference'], unique=False)
    op.create_index('ix_inv_trfr_h_objtype', 'inv_trfr_h', ['objtype'], unique=False)
    op.create_index('ix_inv_trfr_h_id', 'inv_trfr_h', ['id'], unique=False)
    op.create_index('ix_inv_trfr_h_docstatus', 'inv_trfr_h', ['docstatus'], unique=False)
    op.create_table('inv_receive_h',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='inv_receive_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_receive_h_objtype_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='inv_receive_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inv_receive_h_pkey')
    )
    op.create_index('ix_inv_receive_h_reference', 'inv_receive_h', ['reference'], unique=False)
    op.create_index('ix_inv_receive_h_objtype', 'inv_receive_h', ['objtype'], unique=False)
    op.create_index('ix_inv_receive_h_id', 'inv_receive_h', ['id'], unique=False)
    op.create_index('ix_inv_receive_h_docstatus', 'inv_receive_h', ['docstatus'], unique=False)
    op.create_table('inv_transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inqty', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('outqty', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('whsecode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('whsecode2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_canceled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['item.code'], name='inv_transaction_item_code_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_transaction_objtype_fkey'),
    sa.ForeignKeyConstraint(['uom'], ['uom.code'], name='inv_transaction_uom_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['whsecode'], ['warehouse.code'], name='inv_transaction_whsecode_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['whsecode2'], ['warehouse.code'], name='inv_transaction_whsecode2_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='inv_transaction_pkey')
    )
    op.create_index('ix_inv_transaction_whsecode2', 'inv_transaction', ['whsecode2'], unique=False)
    op.create_index('ix_inv_transaction_whsecode', 'inv_transaction', ['whsecode'], unique=False)
    op.create_index('ix_inv_transaction_transdate', 'inv_transaction', ['transdate'], unique=False)
    op.create_index('ix_inv_transaction_row_id', 'inv_transaction', ['row_id'], unique=False)
    op.create_index('ix_inv_transaction_objtype', 'inv_transaction', ['objtype'], unique=False)
    op.create_index('ix_inv_transaction_item_code', 'inv_transaction', ['item_code'], unique=False)
    op.create_index('ix_inv_transaction_id', 'inv_transaction', ['id'], unique=False)
    op.create_index('ix_inv_transaction_base_id', 'inv_transaction', ['base_id'], unique=False)
    op.create_table('inv_adj_in_h',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_canceled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('canceled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canceled_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.code'], name='inv_adj_in_h_branch_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], name='inv_adj_in_h_canceled_by_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='inv_adj_in_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_adj_in_h_objtype_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='inv_adj_in_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inv_adj_in_h_pkey')
    )
    op.create_index('ix_inv_adj_in_h_reference', 'inv_adj_in_h', ['reference'], unique=False)
    op.create_index('ix_inv_adj_in_h_objtype', 'inv_adj_in_h', ['objtype'], unique=False)
    op.create_index('ix_inv_adj_in_h_id', 'inv_adj_in_h', ['id'], unique=False)
    op.create_index('ix_inv_adj_in_h_hashed_id', 'inv_adj_in_h', ['hashed_id'], unique=False)
    op.create_table('inv_trfr_req_h',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_canceled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('canceled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canceled_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.code'], name='inv_trfr_req_h_branch_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], name='inv_trfr_req_h_canceled_by_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='inv_trfr_req_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_trfr_req_h_objtype_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='inv_trfr_req_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inv_trfr_req_h_pkey')
    )
    op.create_index('ix_inv_trfr_req_h_reference', 'inv_trfr_req_h', ['reference'], unique=False)
    op.create_index('ix_inv_trfr_req_h_objtype', 'inv_trfr_req_h', ['objtype'], unique=False)
    op.create_index('ix_inv_trfr_req_h_id', 'inv_trfr_req_h', ['id'], unique=False)
    op.create_index('ix_inv_trfr_req_h_hashed_id', 'inv_trfr_req_h', ['hashed_id'], unique=False)
    op.create_index('ix_inv_trfr_req_h_docstatus', 'inv_trfr_req_h', ['docstatus'], unique=False)
    op.create_table('inv_adj_out_h',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_canceled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('canceled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canceled_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.code'], name='inv_adj_out_h_branch_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], name='inv_adj_out_h_canceled_by_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='inv_adj_out_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['objtype'], ['object_type.id'], name='inv_adj_out_h_objtype_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='inv_adj_out_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inv_adj_out_h_pkey')
    )
    op.create_index('ix_inv_adj_out_h_reference', 'inv_adj_out_h', ['reference'], unique=False)
    op.create_index('ix_inv_adj_out_h_objtype', 'inv_adj_out_h', ['objtype'], unique=False)
    op.create_index('ix_inv_adj_out_h_id', 'inv_adj_out_h', ['id'], unique=False)
    op.create_index('ix_inv_adj_out_h_hashed_id', 'inv_adj_out_h', ['hashed_id'], unique=False)
    op.create_table('whseinv',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('whsecode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['item.code'], name='whseinv_item_code_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['whsecode'], ['warehouse.code'], name='whseinv_whsecode_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='whseinv_pkey')
    )
    op.create_index('ix_whseinv_whsecode', 'whseinv', ['whsecode'], unique=False)
    op.create_index('ix_whseinv_item_code', 'whseinv', ['item_code'], unique=False)
    op.create_index('ix_whseinv_id', 'whseinv', ['id'], unique=False)
    # ### end Alembic commands ###
