"""latest

Revision ID: 5290d1d412ec
Revises: 5649c567a920
Create Date: 2022-09-18 02:40:59.897589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '5290d1d412ec'
down_revision = '5649c567a920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('pricelist_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'branch', 'pricelist_h', ['pricelist_code'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'pricelist_code')
    # ### end Alembic commands ###
