"""item_group_auth

Revision ID: 65345a822c1e
Revises: a2f93c1bec39
Create Date: 2022-11-02 09:40:00.721198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '65345a822c1e'
down_revision = 'a2f93c1bec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_item_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('item_group_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_last_purc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('grant_avg_value', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id', 'item_group_code')
    )
    op.create_index(op.f('ix_auth_item_group_id'), 'auth_item_group', ['id'], unique=False)
    op.create_index(op.f('ix_auth_item_group_item_group_code'), 'auth_item_group', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_auth_item_group_system_user_id'), 'auth_item_group', ['system_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_item_group_system_user_id'), table_name='auth_item_group')
    op.drop_index(op.f('ix_auth_item_group_item_group_code'), table_name='auth_item_group')
    op.drop_index(op.f('ix_auth_item_group_id'), table_name='auth_item_group')
    op.drop_table('auth_item_group')
    # ### end Alembic commands ###
