"""latest

Revision ID: 6c0a88c79634
Revises: 1cc759386aac
Create Date: 2022-10-22 03:39:48.492465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6c0a88c79634"
down_revision = "1cc759386aac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
