"""latest

Revision ID: 78436d813953
Revises: 9bd0b981aa73
Create Date: 2022-09-13 03:27:02.548941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '78436d813953'
down_revision = '9bd0b981aa73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_branch_is_active', table_name='branch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_branch_is_active', 'branch', ['is_active'], unique=False)
    # ### end Alembic commands ###
