"""latest

Revision ID: 79b29a4faca2
Revises: 6619eec9cb9f
Create Date: 2022-10-19 08:17:06.216717

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '79b29a4faca2'
down_revision = '6619eec9cb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_auth', sa.Column('full', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sys_auth', sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sys_auth', sa.Column('create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sys_auth', sa.Column('approve', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index('ix_sys_auth_auth', table_name='sys_auth')
    op.create_index(op.f('ix_sys_auth_approve'), 'sys_auth', ['approve'], unique=False)
    op.create_index(op.f('ix_sys_auth_create'), 'sys_auth', ['create'], unique=False)
    op.create_index(op.f('ix_sys_auth_full'), 'sys_auth', ['full'], unique=False)
    op.create_index(op.f('ix_sys_auth_read'), 'sys_auth', ['read'], unique=False)
    op.drop_column('sys_auth', 'auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_auth', sa.Column('auth', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sys_auth_read'), table_name='sys_auth')
    op.drop_index(op.f('ix_sys_auth_full'), table_name='sys_auth')
    op.drop_index(op.f('ix_sys_auth_create'), table_name='sys_auth')
    op.drop_index(op.f('ix_sys_auth_approve'), table_name='sys_auth')
    op.create_index('ix_sys_auth_auth', 'sys_auth', ['auth'], unique=False)
    op.drop_column('sys_auth', 'approve')
    op.drop_column('sys_auth', 'create')
    op.drop_column('sys_auth', 'read')
    op.drop_column('sys_auth', 'full')
    # ### end Alembic commands ###
