"""latest

Revision ID: 7cf4f0a5d1eb
Revises: 3661bb26d0a0
Create Date: 2022-10-11 01:23:49.321786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7cf4f0a5d1eb"
down_revision = "3661bb26d0a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
