"""authItemGroupLogs

Revision ID: 7d52c5f163e3
Revises: fb4c5f39fdcc
Create Date: 2022-11-07 15:00:39.537289

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new


# revision identifiers, used by Alembic.
revision = "7d52c5f163e3"
down_revision = "fb4c5f39fdcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_alt_uom_id", table_name="alt_uom")
    op.create_index(op.f("ix_alt_uom_id"), "alt_uom", ["id"], unique=True)
    op.drop_index("ix_auth_item_group_id", table_name="auth_item_group")
    op.create_index(
        op.f("ix_auth_item_group_id"), "auth_item_group", ["id"], unique=True
    )
    op.drop_index("ix_customer_address_id", table_name="customer_address")
    op.create_index(
        op.f("ix_customer_address_id"), "customer_address", ["id"], unique=True
    )
    op.drop_index(
        "ix_price_quotation_attachment_id", table_name="price_quotation_attachment"
    )
    op.create_index(
        op.f("ix_price_quotation_attachment_id"),
        "price_quotation_attachment",
        ["id"],
        unique=True,
    )
    op.drop_index("ix_price_quotation_comment_id", table_name="price_quotation_comment")
    op.create_index(
        op.f("ix_price_quotation_comment_id"),
        "price_quotation_comment",
        ["id"],
        unique=True,
    )
    op.drop_index("ix_price_quotation_h_id", table_name="price_quotation_h")
    op.create_index(
        op.f("ix_price_quotation_h_id"), "price_quotation_h", ["id"], unique=True
    )
    op.drop_index("ix_price_quotation_r_id", table_name="price_quotation_r")
    op.create_index(
        op.f("ix_price_quotation_r_id"), "price_quotation_r", ["id"], unique=True
    )
    op.drop_index("ix_pricelist_r_id", table_name="pricelist_r")
    op.create_index(op.f("ix_pricelist_r_id"), "pricelist_r", ["id"], unique=True)
    op.drop_index("ix_pricelist_r_logs_id", table_name="pricelist_r_logs")
    op.create_index(
        op.f("ix_pricelist_r_logs_id"), "pricelist_r_logs", ["id"], unique=True
    )
    op.drop_index("ix_sys_auth_id", table_name="sys_auth")
    op.create_index(op.f("ix_sys_auth_id"), "sys_auth", ["id"], unique=True)
    op.drop_index("ix_system_user_id", table_name="system_user")
    op.create_index(op.f("ix_system_user_id"), "system_user", ["id"], unique=True)
    op.create_table(
        "auth_item_group_logs",
        sa.Column("system_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "item_group_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "grant_last_purc",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "grant_avg_value",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_group_auth_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_group_auth_id"], ["auth_item_group.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["item_group_code"], ["item_group.code"], onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["system_user_id"], ["system_user.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index(
        op.f("ix_auth_item_group_logs_item_group_auth_id"),
        "auth_item_group_logs",
        ["item_group_auth_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_item_group_logs_item_group_code"),
        "auth_item_group_logs",
        ["item_group_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_item_group_logs_log_id"),
        "auth_item_group_logs",
        ["log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_item_group_logs_system_user_id"),
        "auth_item_group_logs",
        ["system_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_user_id"), table_name="system_user")
    op.create_index("ix_system_user_id", "system_user", ["id"], unique=False)
    op.drop_index(op.f("ix_sys_auth_id"), table_name="sys_auth")
    op.create_index("ix_sys_auth_id", "sys_auth", ["id"], unique=False)
    op.drop_index(op.f("ix_pricelist_r_logs_id"), table_name="pricelist_r_logs")
    op.create_index("ix_pricelist_r_logs_id", "pricelist_r_logs", ["id"], unique=False)
    op.drop_index(op.f("ix_pricelist_r_id"), table_name="pricelist_r")
    op.create_index("ix_pricelist_r_id", "pricelist_r", ["id"], unique=False)
    op.drop_index(op.f("ix_price_quotation_r_id"), table_name="price_quotation_r")
    op.create_index(
        "ix_price_quotation_r_id", "price_quotation_r", ["id"], unique=False
    )
    op.drop_index(op.f("ix_price_quotation_h_id"), table_name="price_quotation_h")
    op.create_index(
        "ix_price_quotation_h_id", "price_quotation_h", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_price_quotation_comment_id"), table_name="price_quotation_comment"
    )
    op.create_index(
        "ix_price_quotation_comment_id", "price_quotation_comment", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_price_quotation_attachment_id"),
        table_name="price_quotation_attachment",
    )
    op.create_index(
        "ix_price_quotation_attachment_id",
        "price_quotation_attachment",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_customer_address_id"), table_name="customer_address")
    op.create_index("ix_customer_address_id", "customer_address", ["id"], unique=False)
    op.drop_index(op.f("ix_auth_item_group_id"), table_name="auth_item_group")
    op.create_index("ix_auth_item_group_id", "auth_item_group", ["id"], unique=False)
    op.drop_index(op.f("ix_alt_uom_id"), table_name="alt_uom")
    op.create_index("ix_alt_uom_id", "alt_uom", ["id"], unique=False)
    op.drop_index(
        op.f("ix_auth_item_group_logs_system_user_id"),
        table_name="auth_item_group_logs",
    )
    op.drop_index(
        op.f("ix_auth_item_group_logs_log_id"), table_name="auth_item_group_logs"
    )
    op.drop_index(
        op.f("ix_auth_item_group_logs_item_group_code"),
        table_name="auth_item_group_logs",
    )
    op.drop_index(
        op.f("ix_auth_item_group_logs_item_group_auth_id"),
        table_name="auth_item_group_logs",
    )
    op.drop_table("auth_item_group_logs")
    # ### end Alembic commands ###
