"""item_group_auth

Revision ID: 8ceb8bcbc3f4
Revises: 65345a822c1e
Create Date: 2022-11-02 10:23:52.469044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '8ceb8bcbc3f4'
down_revision = '65345a822c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
