"""latest

Revision ID: 8eaec73c206f
Revises: 79b29a4faca2
Create Date: 2022-10-19 08:23:41.571489

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '8eaec73c206f'
down_revision = '79b29a4faca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
