"""latest

Revision ID: 9445258ccf9e
Revises: c65ccfd932dd
Create Date: 2022-09-24 02:53:54.967237

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '9445258ccf9e'
down_revision = 'c65ccfd932dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_term',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_payment_term_code'), 'payment_term', ['code'], unique=True)
    op.create_index(op.f('ix_payment_term_description'), 'payment_term', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_term_description'), table_name='payment_term')
    op.drop_index(op.f('ix_payment_term_code'), table_name='payment_term')
    op.drop_table('payment_term')
    # ### end Alembic commands ###
