"""latest

Revision ID: a22fcfafe1c1
Revises: 6f4bea7a2be4
Create Date: 2022-09-15 03:10:39.815187

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'a22fcfafe1c1'
down_revision = '6f4bea7a2be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_h', 'dispatching_branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_h', 'dispatching_branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
