"""item_group_auth

Revision ID: a2f93c1bec39
Revises: 741ee9149ab6
Create Date: 2022-11-02 09:05:40.573386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a2f93c1bec39"
down_revision = "741ee9149ab6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
