"""latest

Revision ID: a45367a1f187
Revises: 39cf4119dd2f
Create Date: 2022-10-17 11:56:56.037863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'a45367a1f187'
down_revision = '39cf4119dd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
