"""latest

Revision ID: a952654259e2
Revises: f0ea5b7d631b
Create Date: 2022-10-25 08:27:05.384714

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'a952654259e2'
down_revision = 'f0ea5b7d631b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist_r_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_purchase_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('avg_sap_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('pricelist_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('logistics_cost', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('uom_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('pricelist_row_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['item.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['pricelist_code'], ['pricelist_h.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['pricelist_row_id'], ['pricelist_r.id'], ),
    sa.ForeignKeyConstraint(['uom_code'], ['uom.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricelist_r_logs_id'), 'pricelist_r_logs', ['id'], unique=False)
    op.create_index(op.f('ix_pricelist_r_logs_item_code'), 'pricelist_r_logs', ['item_code'], unique=False)
    op.create_index(op.f('ix_pricelist_r_logs_pricelist_code'), 'pricelist_r_logs', ['pricelist_code'], unique=False)
    op.create_index(op.f('ix_pricelist_r_logs_pricelist_row_id'), 'pricelist_r_logs', ['pricelist_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricelist_r_logs_pricelist_row_id'), table_name='pricelist_r_logs')
    op.drop_index(op.f('ix_pricelist_r_logs_pricelist_code'), table_name='pricelist_r_logs')
    op.drop_index(op.f('ix_pricelist_r_logs_item_code'), table_name='pricelist_r_logs')
    op.drop_index(op.f('ix_pricelist_r_logs_id'), table_name='pricelist_r_logs')
    op.drop_table('pricelist_r_logs')
    # ### end Alembic commands ###
