"""latest

Revision ID: acb930b517a8
Revises: ec871b79d9c2
Create Date: 2022-09-26 07:37:18.298116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'acb930b517a8'
down_revision = 'ec871b79d9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_address', 'contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_address', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
