"""latest

Revision ID: af58a181befb
Revises: 82590b3fe0cd
Create Date: 2022-11-04 15:15:24.968907

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'af58a181befb'
down_revision = '82590b3fe0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['location'], ['branch.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['payment_terms'], ['payment_terms.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_customer_card_name'), 'customer', ['card_name'], unique=False)
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_location'), 'customer', ['location'], unique=False)
    op.create_foreign_key(None, 'customer_address', 'customer', ['customer_code'], ['code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'price_quotation_h', 'customer', ['customer_code'], ['code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_quotation_h', type_='foreignkey')
    op.drop_constraint(None, 'customer_address', type_='foreignkey')
    op.drop_index(op.f('ix_customer_location'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_index(op.f('ix_customer_card_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
