"""latest

Revision ID: b76cc8589cbb
Revises: 0d83fcdfd75b
Create Date: 2022-10-17 09:27:44.355091

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new


# revision identifiers, used by Alembic.
revision = "b76cc8589cbb"
down_revision = "0d83fcdfd75b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
