"""latest

Revision ID: ca6746d93a8a
Revises: 
Create Date: 2022-09-12 10:42:11.003835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new


# revision identifiers, used by Alembic.
revision = "ca6746d93a8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_user",
        sa.Column(
            "is_active", sa.BOOLEAN(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("branch_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        # sa.ForeignKeyConstraint(['branch_code'], ['branch.code'], onupdate='CASCADE'),
        # sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
        # sa.ForeignKeyConstraint(['position_code'], ['position.code'], onupdate='CASCADE'),
        # sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "branch",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("series_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_branch_code"), "branch", ["code"], unique=True)
    op.create_index(
        op.f("ix_branch_description"), "branch", ["description"], unique=False
    )
    op.create_index(op.f("ix_branch_is_active"), "branch", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_branch_series_code"), "branch", ["series_code"], unique=True
    )
    op.create_table(
        "object_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_object_type_id"), "object_type", ["id"], unique=False)
    op.create_index(op.f("ix_object_type_name"), "object_type", ["name"], unique=True)
    op.create_table(
        "position",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_position_code"), "position", ["code"], unique=True)
    op.create_index(
        op.f("ix_position_description"), "position", ["description"], unique=False
    )

    op.create_index(
        op.f("ix_system_user_branch_code"), "system_user", ["branch_code"], unique=False
    )
    op.create_index(op.f("ix_system_user_email"), "system_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_system_user_first_name"), "system_user", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_system_user_last_name"), "system_user", ["last_name"], unique=False
    )
    op.create_index(
        op.f("ix_system_user_position_code"),
        "system_user",
        ["position_code"],
        unique=False,
    )
    op.create_table(
        "inv_adj_in_h",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transdate", sa.DateTime(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_canceled", sa.DateTime(), nullable=True),
        sa.Column("canceled_by", sa.Integer(), nullable=True),
        sa.Column(
            "canceled_remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("docstatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch"], ["branch.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["canceled_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_adj_in_h_hashed_id"), "inv_adj_in_h", ["hashed_id"], unique=True
    )
    op.create_index(
        op.f("ix_inv_adj_in_h_objtype"), "inv_adj_in_h", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_in_h_reference"), "inv_adj_in_h", ["reference"], unique=True
    )
    op.create_table(
        "inv_adj_out_h",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transdate", sa.DateTime(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_canceled", sa.DateTime(), nullable=True),
        sa.Column("canceled_by", sa.Integer(), nullable=True),
        sa.Column(
            "canceled_remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("docstatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch"], ["branch.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["canceled_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_adj_out_h_hashed_id"), "inv_adj_out_h", ["hashed_id"], unique=True
    )
    op.create_index(
        op.f("ix_inv_adj_out_h_objtype"), "inv_adj_out_h", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_out_h_reference"), "inv_adj_out_h", ["reference"], unique=True
    )
    op.create_table(
        "inv_receive_h",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transdate", sa.DateTime(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("docstatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_receive_h_docstatus"), "inv_receive_h", ["docstatus"], unique=False
    )
    op.create_index(
        op.f("ix_inv_receive_h_objtype"), "inv_receive_h", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_receive_h_reference"), "inv_receive_h", ["reference"], unique=True
    )
    op.create_table(
        "inv_trfr_h",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transdate", sa.DateTime(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("docstatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_trfr_h_docstatus"), "inv_trfr_h", ["docstatus"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_h_objtype"), "inv_trfr_h", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_h_reference"), "inv_trfr_h", ["reference"], unique=True
    )
    op.create_table(
        "inv_trfr_req_h",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transdate", sa.DateTime(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hashed_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_canceled", sa.DateTime(), nullable=True),
        sa.Column("canceled_by", sa.Integer(), nullable=True),
        sa.Column(
            "canceled_remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("docstatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch"], ["branch.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["canceled_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_trfr_req_h_docstatus"),
        "inv_trfr_req_h",
        ["docstatus"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_trfr_req_h_hashed_id"),
        "inv_trfr_req_h",
        ["hashed_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_inv_trfr_req_h_objtype"), "inv_trfr_req_h", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_req_h_reference"),
        "inv_trfr_req_h",
        ["reference"],
        unique=True,
    )
    op.create_table(
        "item_group",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_item_group_code"), "item_group", ["code"], unique=False)
    op.create_index(
        op.f("ix_item_group_description"), "item_group", ["description"], unique=False
    )
    op.create_index(
        op.f("ix_item_group_is_active"), "item_group", ["is_active"], unique=False
    )
    op.create_table(
        "system_user_branch",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "is_assigned", sa.BOOLEAN(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column("system_user_id", sa.Integer(), nullable=False),
        sa.Column("branch_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["branch_code"], ["branch.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["system_user_id"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_user_branch_branch_code"),
        "system_user_branch",
        ["branch_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_user_branch_system_user_id"),
        "system_user_branch",
        ["system_user_id"],
        unique=False,
    )
    op.create_table(
        "uom",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_uom_code"), "uom", ["code"], unique=False)
    op.create_index(op.f("ix_uom_description"), "uom", ["description"], unique=False)
    op.create_table(
        "warehouse",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("branch_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_allowed_negative", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch_code"], ["branch.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_warehouse_branch_code"), "warehouse", ["branch_code"], unique=False
    )
    op.create_index(op.f("ix_warehouse_code"), "warehouse", ["code"], unique=False)
    op.create_index(
        op.f("ix_warehouse_description"), "warehouse", ["description"], unique=False
    )
    op.create_index(
        op.f("ix_warehouse_is_active"), "warehouse", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_warehouse_is_allowed_negative"),
        "warehouse",
        ["is_allowed_negative"],
        unique=False,
    )
    op.create_table(
        "uom_group",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["base_uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_uom_group_code"), "uom_group", ["code"], unique=False)
    op.create_index(
        op.f("ix_uom_group_description"), "uom_group", ["description"], unique=False
    )
    op.create_table(
        "alt_uom",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uom_group_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("alt_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("alt_uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("base_uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["alt_uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["base_uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uom_group_code"],
            ["uom_group.code"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_alt_uom_uom_group_code"), "alt_uom", ["uom_group_code"], unique=False
    )
    op.create_table(
        "item",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("item_group_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uom_group_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sale_uom_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "purchasing_uom_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("inv_uom_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_allowed_negative", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inv_uom_code"],
            ["uom.code"],
        ),
        sa.ForeignKeyConstraint(
            ["item_group_code"],
            ["item_group.code"],
        ),
        sa.ForeignKeyConstraint(
            ["purchasing_uom_code"],
            ["uom.code"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_uom_code"],
            ["uom.code"],
        ),
        sa.ForeignKeyConstraint(
            ["uom_group_code"],
            ["uom_group.code"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_item_barcode"), "item", ["barcode"], unique=True)
    op.create_index(op.f("ix_item_code"), "item", ["code"], unique=False)
    op.create_index(op.f("ix_item_description"), "item", ["description"], unique=False)
    op.create_index(
        op.f("ix_item_inv_uom_code"), "item", ["inv_uom_code"], unique=False
    )
    op.create_index(
        op.f("ix_item_item_group_code"), "item", ["item_group_code"], unique=False
    )
    op.create_index(
        op.f("ix_item_purchasing_uom_code"),
        "item",
        ["purchasing_uom_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_sale_uom_code"), "item", ["sale_uom_code"], unique=False
    )
    op.create_index(
        op.f("ix_item_uom_group_code"), "item", ["uom_group_code"], unique=False
    )
    op.create_table(
        "inv_adj_in_r",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("linestatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("inv_qty", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["inv_adj_in_h.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_doc_id"), "inv_adj_in_r", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_item_code"), "inv_adj_in_r", ["item_code"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_item_description"),
        "inv_adj_in_r",
        ["item_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_objtype"), "inv_adj_in_r", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_whsecode"), "inv_adj_in_r", ["whsecode"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_in_r_whsecode2"), "inv_adj_in_r", ["whsecode2"], unique=False
    )
    op.create_table(
        "inv_adj_out_r",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("linestatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("inv_qty", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["inv_adj_out_h.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_doc_id"), "inv_adj_out_r", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_item_code"), "inv_adj_out_r", ["item_code"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_item_description"),
        "inv_adj_out_r",
        ["item_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_objtype"), "inv_adj_out_r", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_whsecode"), "inv_adj_out_r", ["whsecode"], unique=False
    )
    op.create_index(
        op.f("ix_inv_adj_out_r_whsecode2"), "inv_adj_out_r", ["whsecode2"], unique=False
    )
    op.create_table(
        "inv_receive_r",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_id", sa.Integer(), nullable=True),
        sa.Column("base_objtype", sa.Integer(), nullable=True),
        sa.Column("base_row_id", sa.Integer(), nullable=True),
        sa.Column("base_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("linestatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inv_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(["doc_id"], ["inv_receive_h.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_receive_r_doc_id"), "inv_receive_r", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_inv_receive_r_item_description"),
        "inv_receive_r",
        ["item_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_receive_r_linestatus"),
        "inv_receive_r",
        ["linestatus"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_receive_r_objtype"), "inv_receive_r", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_receive_r_whsecode"), "inv_receive_r", ["whsecode"], unique=False
    )
    op.create_index(
        op.f("ix_inv_receive_r_whsecode2"), "inv_receive_r", ["whsecode2"], unique=False
    )
    op.create_table(
        "inv_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("base_id", sa.Integer(), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column(
            "transdate", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("inqty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("outqty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "is_canceled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_transaction_base_id"), "inv_transaction", ["base_id"], unique=False
    )
    op.create_index(
        op.f("ix_inv_transaction_item_code"),
        "inv_transaction",
        ["item_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_transaction_objtype"), "inv_transaction", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_transaction_row_id"), "inv_transaction", ["row_id"], unique=False
    )
    op.create_index(
        op.f("ix_inv_transaction_transdate"),
        "inv_transaction",
        ["transdate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_transaction_whsecode"),
        "inv_transaction",
        ["whsecode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_transaction_whsecode2"),
        "inv_transaction",
        ["whsecode2"],
        unique=False,
    )
    op.create_table(
        "inv_trfr_r",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_id", sa.Integer(), nullable=True),
        sa.Column("base_objtype", sa.Integer(), nullable=True),
        sa.Column("base_row_id", sa.Integer(), nullable=True),
        sa.Column("base_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("linestatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("inv_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_objtype"], ["object_type.id"], onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(["doc_id"], ["inv_trfr_h.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["system_user.id"],
        ),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_trfr_r_item_description"),
        "inv_trfr_r",
        ["item_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_trfr_r_linestatus"), "inv_trfr_r", ["linestatus"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_r_objtype"), "inv_trfr_r", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_r_whsecode"), "inv_trfr_r", ["whsecode"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_r_whsecode2"), "inv_trfr_r", ["whsecode2"], unique=False
    )
    op.create_table(
        "inv_trfr_req_r",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("whsecode2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("uom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("objtype", sa.Integer(), nullable=True),
        sa.Column("linestatus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("inv_qty", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["doc_id"], ["inv_trfr_req_h.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["objtype"],
            ["object_type.id"],
        ),
        sa.ForeignKeyConstraint(["uom"], ["uom.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode2"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_inv_trfr_req_r_item_description"),
        "inv_trfr_req_r",
        ["item_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_trfr_req_r_linestatus"),
        "inv_trfr_req_r",
        ["linestatus"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inv_trfr_req_r_objtype"), "inv_trfr_req_r", ["objtype"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_req_r_whsecode"), "inv_trfr_req_r", ["whsecode"], unique=False
    )
    op.create_index(
        op.f("ix_inv_trfr_req_r_whsecode2"),
        "inv_trfr_req_r",
        ["whsecode2"],
        unique=False,
    )
    op.create_table(
        "whseinv",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("whsecode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["item_code"], ["item.code"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["whsecode"], ["warehouse.code"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_whseinv_item_code"), "whseinv", ["item_code"], unique=False
    )
    op.create_index(op.f("ix_whseinv_whsecode"), "whseinv", ["whsecode"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whseinv_whsecode"), table_name="whseinv")
    op.drop_index(op.f("ix_whseinv_item_code"), table_name="whseinv")
    op.drop_table("whseinv")
    op.drop_index(op.f("ix_inv_trfr_req_r_whsecode2"), table_name="inv_trfr_req_r")
    op.drop_index(op.f("ix_inv_trfr_req_r_whsecode"), table_name="inv_trfr_req_r")
    op.drop_index(op.f("ix_inv_trfr_req_r_objtype"), table_name="inv_trfr_req_r")
    op.drop_index(op.f("ix_inv_trfr_req_r_linestatus"), table_name="inv_trfr_req_r")
    op.drop_index(
        op.f("ix_inv_trfr_req_r_item_description"), table_name="inv_trfr_req_r"
    )
    op.drop_table("inv_trfr_req_r")
    op.drop_index(op.f("ix_inv_trfr_r_whsecode2"), table_name="inv_trfr_r")
    op.drop_index(op.f("ix_inv_trfr_r_whsecode"), table_name="inv_trfr_r")
    op.drop_index(op.f("ix_inv_trfr_r_objtype"), table_name="inv_trfr_r")
    op.drop_index(op.f("ix_inv_trfr_r_linestatus"), table_name="inv_trfr_r")
    op.drop_index(op.f("ix_inv_trfr_r_item_description"), table_name="inv_trfr_r")
    op.drop_table("inv_trfr_r")
    op.drop_index(op.f("ix_inv_transaction_whsecode2"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_whsecode"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_transdate"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_row_id"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_objtype"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_item_code"), table_name="inv_transaction")
    op.drop_index(op.f("ix_inv_transaction_base_id"), table_name="inv_transaction")
    op.drop_table("inv_transaction")
    op.drop_index(op.f("ix_inv_receive_r_whsecode2"), table_name="inv_receive_r")
    op.drop_index(op.f("ix_inv_receive_r_whsecode"), table_name="inv_receive_r")
    op.drop_index(op.f("ix_inv_receive_r_objtype"), table_name="inv_receive_r")
    op.drop_index(op.f("ix_inv_receive_r_linestatus"), table_name="inv_receive_r")
    op.drop_index(op.f("ix_inv_receive_r_item_description"), table_name="inv_receive_r")
    op.drop_index(op.f("ix_inv_receive_r_doc_id"), table_name="inv_receive_r")
    op.drop_table("inv_receive_r")
    op.drop_index(op.f("ix_inv_adj_out_r_whsecode2"), table_name="inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_out_r_whsecode"), table_name="inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_out_r_objtype"), table_name="inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_out_r_item_description"), table_name="inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_out_r_item_code"), table_name="inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_out_r_doc_id"), table_name="inv_adj_out_r")
    op.drop_table("inv_adj_out_r")
    op.drop_index(op.f("ix_inv_adj_in_r_whsecode2"), table_name="inv_adj_in_r")
    op.drop_index(op.f("ix_inv_adj_in_r_whsecode"), table_name="inv_adj_in_r")
    op.drop_index(op.f("ix_inv_adj_in_r_objtype"), table_name="inv_adj_in_r")
    op.drop_index(op.f("ix_inv_adj_in_r_item_description"), table_name="inv_adj_in_r")
    op.drop_index(op.f("ix_inv_adj_in_r_item_code"), table_name="inv_adj_in_r")
    op.drop_index(op.f("ix_inv_adj_in_r_doc_id"), table_name="inv_adj_in_r")
    op.drop_table("inv_adj_in_r")
    op.drop_index(op.f("ix_item_uom_group_code"), table_name="item")
    op.drop_index(op.f("ix_item_sale_uom_code"), table_name="item")
    op.drop_index(op.f("ix_item_purchasing_uom_code"), table_name="item")
    op.drop_index(op.f("ix_item_item_group_code"), table_name="item")
    op.drop_index(op.f("ix_item_inv_uom_code"), table_name="item")
    op.drop_index(op.f("ix_item_description"), table_name="item")
    op.drop_index(op.f("ix_item_code"), table_name="item")
    op.drop_index(op.f("ix_item_barcode"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_alt_uom_uom_group_code"), table_name="alt_uom")
    op.drop_table("alt_uom")
    op.drop_index(op.f("ix_uom_group_description"), table_name="uom_group")
    op.drop_index(op.f("ix_uom_group_code"), table_name="uom_group")
    op.drop_table("uom_group")
    op.drop_index(op.f("ix_warehouse_is_allowed_negative"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_is_active"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_description"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_code"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_branch_code"), table_name="warehouse")
    op.drop_table("warehouse")
    op.drop_index(op.f("ix_uom_description"), table_name="uom")
    op.drop_index(op.f("ix_uom_code"), table_name="uom")
    op.drop_table("uom")
    op.drop_index(
        op.f("ix_system_user_branch_system_user_id"), table_name="system_user_branch"
    )
    op.drop_index(
        op.f("ix_system_user_branch_branch_code"), table_name="system_user_branch"
    )
    op.drop_table("system_user_branch")
    op.drop_index(op.f("ix_item_group_is_active"), table_name="item_group")
    op.drop_index(op.f("ix_item_group_description"), table_name="item_group")
    op.drop_index(op.f("ix_item_group_code"), table_name="item_group")
    op.drop_table("item_group")
    op.drop_index(op.f("ix_inv_trfr_req_h_reference"), table_name="inv_trfr_req_h")
    op.drop_index(op.f("ix_inv_trfr_req_h_objtype"), table_name="inv_trfr_req_h")
    op.drop_index(op.f("ix_inv_trfr_req_h_hashed_id"), table_name="inv_trfr_req_h")
    op.drop_index(op.f("ix_inv_trfr_req_h_docstatus"), table_name="inv_trfr_req_h")
    op.drop_table("inv_trfr_req_h")
    op.drop_index(op.f("ix_inv_trfr_h_reference"), table_name="inv_trfr_h")
    op.drop_index(op.f("ix_inv_trfr_h_objtype"), table_name="inv_trfr_h")
    op.drop_index(op.f("ix_inv_trfr_h_docstatus"), table_name="inv_trfr_h")
    op.drop_table("inv_trfr_h")
    op.drop_index(op.f("ix_inv_receive_h_reference"), table_name="inv_receive_h")
    op.drop_index(op.f("ix_inv_receive_h_objtype"), table_name="inv_receive_h")
    op.drop_index(op.f("ix_inv_receive_h_docstatus"), table_name="inv_receive_h")
    op.drop_table("inv_receive_h")
    op.drop_index(op.f("ix_inv_adj_out_h_reference"), table_name="inv_adj_out_h")
    op.drop_index(op.f("ix_inv_adj_out_h_objtype"), table_name="inv_adj_out_h")
    op.drop_index(op.f("ix_inv_adj_out_h_hashed_id"), table_name="inv_adj_out_h")
    op.drop_table("inv_adj_out_h")
    op.drop_index(op.f("ix_inv_adj_in_h_reference"), table_name="inv_adj_in_h")
    op.drop_index(op.f("ix_inv_adj_in_h_objtype"), table_name="inv_adj_in_h")
    op.drop_index(op.f("ix_inv_adj_in_h_hashed_id"), table_name="inv_adj_in_h")
    op.drop_table("inv_adj_in_h")
    op.drop_index(op.f("ix_system_user_position_code"), table_name="system_user")
    op.drop_index(op.f("ix_system_user_last_name"), table_name="system_user")
    op.drop_index(op.f("ix_system_user_first_name"), table_name="system_user")
    op.drop_index(op.f("ix_system_user_email"), table_name="system_user")
    op.drop_index(op.f("ix_system_user_branch_code"), table_name="system_user")
    op.drop_table("system_user")
    op.drop_index(op.f("ix_position_description"), table_name="position")
    op.drop_index(op.f("ix_position_code"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_object_type_name"), table_name="object_type")
    op.drop_index(op.f("ix_object_type_id"), table_name="object_type")
    op.drop_table("object_type")
    op.drop_index(op.f("ix_branch_series_code"), table_name="branch")
    op.drop_index(op.f("ix_branch_is_active"), table_name="branch")
    op.drop_index(op.f("ix_branch_description"), table_name="branch")
    op.drop_index(op.f("ix_branch_code"), table_name="branch")
    op.drop_table("branch")
    # ### end Alembic commands ###
