"""latest

Revision ID: cc2e4926924f
Revises: 2e717573fb84
Create Date: 2022-10-07 03:07:34.128652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'cc2e4926924f'
down_revision = '2e717573fb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_quotation_h', sa.Column('date_approved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_quotation_h', 'date_approved')
    # ### end Alembic commands ###
