"""latest

Revision ID: d2a7d0724685
Revises: 329fcefbc3fb
Create Date: 2022-11-09 20:19:05.000469

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'd2a7d0724685'
down_revision = '329fcefbc3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
