"""latest

Revision ID: ec871b79d9c2
Revises: 2b036a575378
Create Date: 2022-09-24 14:08:54.507854

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'ec871b79d9c2'
down_revision = '2b036a575378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_customer_name', table_name='customer')
    op.create_index(op.f('ix_customer_full_name'), 'customer', ['full_name'], unique=False)
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customer_full_name'), table_name='customer')
    op.create_index('ix_customer_name', 'customer', ['name'], unique=False)
    op.drop_column('customer', 'full_name')
    # ### end Alembic commands ###
