"""latest

Revision ID: f069cae6bcac
Revises: 8eaec73c206f
Create Date: 2022-10-19 08:39:54.392997

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'f069cae6bcac'
down_revision = '8eaec73c206f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
