"""pricelist

Revision ID: f33291b8b63e
Revises: 1399b91195b2
Create Date: 2022-09-14 06:52:37.531970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'f33291b8b63e'
down_revision = '1399b91195b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
