"""latest

Revision ID: 0bc257d06914
Revises: 7b97de53c906
Create Date: 2022-11-10 11:23:47.557135

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '0bc257d06914'
down_revision = '7b97de53c906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('with_sap', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('customer', 'has_sap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('has_sap', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('customer', 'with_sap')
    # ### end Alembic commands ###
