"""pricelist

Revision ID: 1399b91195b2
Revises: a02e36803c70
Create Date: 2022-09-14 05:35:10.896458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '1399b91195b2'
down_revision = 'a02e36803c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist_h',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_pricelist_h_code'), 'pricelist_h', ['code'], unique=True)
    op.create_table('pricelist_r',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pricelist_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricelist_r_id'), 'pricelist_r', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricelist_r_id'), table_name='pricelist_r')
    op.drop_table('pricelist_r')
    op.drop_index(op.f('ix_pricelist_h_code'), table_name='pricelist_h')
    op.drop_table('pricelist_h')
    # ### end Alembic commands ###
