"""latest

Revision ID: 2909dc0d8a7c
Revises: 69ecd4680ed9
Create Date: 2022-09-22 10:49:21.968216

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '2909dc0d8a7c'
down_revision = '69ecd4680ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_r', sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order_r', 'item_description')
    # ### end Alembic commands ###
