"""latest

Revision ID: 2a42588ce481
Revises: ca6746d93a8a
Create Date: 2022-09-12 10:44:04.254567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '2a42588ce481'
down_revision = 'ca6746d93a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alt_uom', ['id'])
    op.create_unique_constraint(None, 'inv_adj_in_h', ['id'])
    op.create_unique_constraint(None, 'inv_adj_in_r', ['id'])
    op.create_unique_constraint(None, 'inv_adj_out_h', ['id'])
    op.create_unique_constraint(None, 'inv_adj_out_r', ['id'])
    op.create_unique_constraint(None, 'inv_receive_h', ['id'])
    op.create_unique_constraint(None, 'inv_receive_r', ['id'])
    op.create_unique_constraint(None, 'inv_transaction', ['id'])
    op.create_unique_constraint(None, 'inv_trfr_h', ['id'])
    op.create_unique_constraint(None, 'inv_trfr_r', ['id'])
    op.create_unique_constraint(None, 'inv_trfr_req_h', ['id'])
    op.create_unique_constraint(None, 'inv_trfr_req_r', ['id'])
    op.create_unique_constraint(None, 'system_user', ['id'])
    op.create_foreign_key(None, 'system_user', 'system_user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'system_user', 'branch', ['branch_code'], ['code'], onupdate='CASCADE')
    op.create_foreign_key(None, 'system_user', 'position', ['position_code'], ['code'], onupdate='CASCADE')
    op.create_foreign_key(None, 'system_user', 'system_user', ['created_by'], ['id'])
    op.create_unique_constraint(None, 'whseinv', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whseinv', type_='unique')
    op.drop_constraint(None, 'system_user', type_='foreignkey')
    op.drop_constraint(None, 'system_user', type_='foreignkey')
    op.drop_constraint(None, 'system_user', type_='foreignkey')
    op.drop_constraint(None, 'system_user', type_='foreignkey')
    op.drop_constraint(None, 'system_user', type_='unique')
    op.drop_constraint(None, 'inv_trfr_req_r', type_='unique')
    op.drop_constraint(None, 'inv_trfr_req_h', type_='unique')
    op.drop_constraint(None, 'inv_trfr_r', type_='unique')
    op.drop_constraint(None, 'inv_trfr_h', type_='unique')
    op.drop_constraint(None, 'inv_transaction', type_='unique')
    op.drop_constraint(None, 'inv_receive_r', type_='unique')
    op.drop_constraint(None, 'inv_receive_h', type_='unique')
    op.drop_constraint(None, 'inv_adj_out_r', type_='unique')
    op.drop_constraint(None, 'inv_adj_out_h', type_='unique')
    op.drop_constraint(None, 'inv_adj_in_r', type_='unique')
    op.drop_constraint(None, 'inv_adj_in_h', type_='unique')
    op.drop_constraint(None, 'alt_uom', type_='unique')
    # ### end Alembic commands ###
