"""latest

Revision ID: 2e717573fb84
Revises: 404e553a4bd9
Create Date: 2022-10-07 02:36:13.632579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '2e717573fb84'
down_revision = '404e553a4bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_quotation_h', sa.Column('sq_number', sa.Integer(), nullable=True))
    op.add_column('price_quotation_h', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_price_quotation_h_sq_number'), 'price_quotation_h', ['sq_number'], unique=False)
    op.create_foreign_key(None, 'price_quotation_h', 'system_user', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_quotation_h', type_='foreignkey')
    op.drop_index(op.f('ix_price_quotation_h_sq_number'), table_name='price_quotation_h')
    op.drop_column('price_quotation_h', 'approved_by')
    op.drop_column('price_quotation_h', 'sq_number')
    # ### end Alembic commands ###
