"""latest

Revision ID: 3661bb26d0a0
Revises: d7953e6ba485
Create Date: 2022-10-11 01:21:12.104584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3661bb26d0a0"
down_revision = "d7953e6ba485"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
