"""latest

Revision ID: 404e553a4bd9
Revises: e80846690065
Create Date: 2022-10-07 00:35:45.329584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '404e553a4bd9'
down_revision = 'e80846690065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_quotation_h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transdate', sa.DateTime(), nullable=True),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_term', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispatching_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('docstatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pq_status', sa.Integer(), nullable=True),
    sa.Column('date_dispatched', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('otherfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_canceled', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('canceled_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['payment_term'], ['payment_term.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_id')
    )
    op.create_index(op.f('ix_price_quotation_h_customer_code'), 'price_quotation_h', ['customer_code'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_delivery_method'), 'price_quotation_h', ['delivery_method'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_dispatching_branch'), 'price_quotation_h', ['dispatching_branch'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_docstatus'), 'price_quotation_h', ['docstatus'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_id'), 'price_quotation_h', ['id'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_payment_term'), 'price_quotation_h', ['payment_term'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_pq_status'), 'price_quotation_h', ['pq_status'], unique=False)
    op.create_index(op.f('ix_price_quotation_h_reference'), 'price_quotation_h', ['reference'], unique=True)
    op.create_table('price_quotation_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_attachment_doc_id'), 'price_quotation_attachment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_attachment_id'), 'price_quotation_attachment', ['id'], unique=False)
    op.create_table('price_quotation_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_comment_doc_id'), 'price_quotation_comment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_comment_id'), 'price_quotation_comment', ['id'], unique=False)
    op.create_table('price_quotation_r',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('srp_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('linetotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['price_quotation_h.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['uom.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_quotation_r_doc_id'), 'price_quotation_r', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_id'), 'price_quotation_r', ['id'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_item_code'), 'price_quotation_r', ['item_code'], unique=False)
    op.create_index(op.f('ix_price_quotation_r_uom'), 'price_quotation_r', ['uom'], unique=False)
    op.drop_index('ix_sales_order_comment_doc_id', table_name='sales_order_comment')
    op.drop_index('ix_sales_order_comment_id', table_name='sales_order_comment')
    op.drop_table('sales_order_comment')
    op.drop_index('ix_sales_order_attachment_doc_id', table_name='sales_order_attachment')
    op.drop_index('ix_sales_order_attachment_id', table_name='sales_order_attachment')
    op.drop_table('sales_order_attachment')
    op.drop_index('ix_sales_order_r_doc_id', table_name='sales_order_r')
    op.drop_index('ix_sales_order_r_id', table_name='sales_order_r')
    op.drop_index('ix_sales_order_r_item_code', table_name='sales_order_r')
    op.drop_index('ix_sales_order_r_uom', table_name='sales_order_r')
    op.drop_table('sales_order_r')
    op.drop_index('ix_sales_order_h_customer_code', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_delivery_method', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_dispatching_branch', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_docstatus', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_id', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_order_status', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_payment_term', table_name='sales_order_h')
    op.drop_index('ix_sales_order_h_reference', table_name='sales_order_h')
    op.drop_table('sales_order_h')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order_h',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sales_order_h_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('transdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dispatching_branch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('docstatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_dispatched', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('gross', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('delfee', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('otherfee', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('confirmed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_confirmed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dispatched_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_canceled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('canceled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canceled_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_term', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], name='sales_order_h_canceled_by_fkey'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['system_user.id'], name='sales_order_h_confirmed_by_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='sales_order_h_created_by_fkey'),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], name='sales_order_h_customer_code_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['system_user.id'], name='sales_order_h_dispatched_by_fkey'),
    sa.ForeignKeyConstraint(['payment_term'], ['payment_term.code'], name='sales_order_h_payment_term_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], name='sales_order_h_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_order_h_pkey'),
    sa.UniqueConstraint('hashed_id', name='sales_order_h_hashed_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_sales_order_h_reference', 'sales_order_h', ['reference'], unique=False)
    op.create_index('ix_sales_order_h_payment_term', 'sales_order_h', ['payment_term'], unique=False)
    op.create_index('ix_sales_order_h_order_status', 'sales_order_h', ['order_status'], unique=False)
    op.create_index('ix_sales_order_h_id', 'sales_order_h', ['id'], unique=False)
    op.create_index('ix_sales_order_h_docstatus', 'sales_order_h', ['docstatus'], unique=False)
    op.create_index('ix_sales_order_h_dispatching_branch', 'sales_order_h', ['dispatching_branch'], unique=False)
    op.create_index('ix_sales_order_h_delivery_method', 'sales_order_h', ['delivery_method'], unique=False)
    op.create_index('ix_sales_order_h_customer_code', 'sales_order_h', ['customer_code'], unique=False)
    op.create_table('sales_order_r',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('srp_price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('linetotal', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('item_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], name='sales_order_r_doc_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['uom.code'], name='sales_order_r_uom_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sales_order_r_pkey')
    )
    op.create_index('ix_sales_order_r_uom', 'sales_order_r', ['uom'], unique=False)
    op.create_index('ix_sales_order_r_item_code', 'sales_order_r', ['item_code'], unique=False)
    op.create_index('ix_sales_order_r_id', 'sales_order_r', ['id'], unique=False)
    op.create_index('ix_sales_order_r_doc_id', 'sales_order_r', ['doc_id'], unique=False)
    op.create_table('sales_order_attachment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='sales_order_attachment_created_by_fkey'),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], name='sales_order_attachment_doc_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sales_order_attachment_pkey')
    )
    op.create_index('ix_sales_order_attachment_id', 'sales_order_attachment', ['id'], unique=False)
    op.create_index('ix_sales_order_attachment_doc_id', 'sales_order_attachment', ['doc_id'], unique=False)
    op.create_table('sales_order_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], name='sales_order_comment_created_by_fkey'),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], name='sales_order_comment_doc_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sales_order_comment_pkey')
    )
    op.create_index('ix_sales_order_comment_id', 'sales_order_comment', ['id'], unique=False)
    op.create_index('ix_sales_order_comment_doc_id', 'sales_order_comment', ['doc_id'], unique=False)
    op.drop_index(op.f('ix_price_quotation_r_uom'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_item_code'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_id'), table_name='price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_r_doc_id'), table_name='price_quotation_r')
    op.drop_table('price_quotation_r')
    op.drop_index(op.f('ix_price_quotation_comment_id'), table_name='price_quotation_comment')
    op.drop_index(op.f('ix_price_quotation_comment_doc_id'), table_name='price_quotation_comment')
    op.drop_table('price_quotation_comment')
    op.drop_index(op.f('ix_price_quotation_attachment_id'), table_name='price_quotation_attachment')
    op.drop_index(op.f('ix_price_quotation_attachment_doc_id'), table_name='price_quotation_attachment')
    op.drop_table('price_quotation_attachment')
    op.drop_index(op.f('ix_price_quotation_h_reference'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_pq_status'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_payment_term'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_id'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_docstatus'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_dispatching_branch'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_delivery_method'), table_name='price_quotation_h')
    op.drop_index(op.f('ix_price_quotation_h_customer_code'), table_name='price_quotation_h')
    op.drop_table('price_quotation_h')
    # ### end Alembic commands ###
