"""sales_order

Revision ID: 42b2c98b204e
Revises: b5695075e75d
Create Date: 2022-09-14 01:18:20.265132

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '42b2c98b204e'
down_revision = 'b5695075e75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_inv_uom_code', table_name='item')
    op.drop_index('ix_item_purchasing_uom_code', table_name='item')
    op.drop_index('ix_item_uom_group_code', table_name='item')
    op.drop_constraint('item_uom_group_code_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_inv_uom_code_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_purchasing_uom_code_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'purchasing_uom_code')
    op.drop_column('item', 'uom_group_code')
    op.drop_column('item', 'inv_uom_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('inv_uom_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('uom_group_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('purchasing_uom_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_purchasing_uom_code_fkey', 'item', 'uom', ['purchasing_uom_code'], ['code'])
    op.create_foreign_key('item_inv_uom_code_fkey', 'item', 'uom', ['inv_uom_code'], ['code'])
    op.create_foreign_key('item_uom_group_code_fkey', 'item', 'uom_group', ['uom_group_code'], ['code'])
    op.create_index('ix_item_uom_group_code', 'item', ['uom_group_code'], unique=False)
    op.create_index('ix_item_purchasing_uom_code', 'item', ['purchasing_uom_code'], unique=False)
    op.create_index('ix_item_inv_uom_code', 'item', ['inv_uom_code'], unique=False)
    # ### end Alembic commands ###
