"""latest

Revision ID: 467ca1e1ad11
Revises: 0bc257d06914
Create Date: 2022-11-11 16:21:51.227932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '467ca1e1ad11'
down_revision = '0bc257d06914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_number', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_version_app_name'), 'app_version', ['app_name'], unique=False)
    op.create_index(op.f('ix_app_version_build_number'), 'app_version', ['build_number'], unique=False)
    op.create_index(op.f('ix_app_version_id'), 'app_version', ['id'], unique=True)
    op.create_index(op.f('ix_app_version_link'), 'app_version', ['link'], unique=False)
    op.create_index(op.f('ix_app_version_package_name'), 'app_version', ['package_name'], unique=False)
    op.create_index(op.f('ix_app_version_platform'), 'app_version', ['platform'], unique=False)
    op.create_index(op.f('ix_app_version_version'), 'app_version', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_version_version'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_platform'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_package_name'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_link'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_id'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_build_number'), table_name='app_version')
    op.drop_index(op.f('ix_app_version_app_name'), table_name='app_version')
    op.drop_table('app_version')
    # ### end Alembic commands ###
