"""latest

Revision ID: 68d7c515b238
Revises: 2909dc0d8a7c
Create Date: 2022-09-22 10:52:51.727759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '68d7c515b238'
down_revision = '2909dc0d8a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
