"""itemGroupuserAuth

Revision ID: 741ee9149ab6
Revises: bf5a313d0dc7
Create Date: 2022-10-29 13:18:58.030391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '741ee9149ab6'
down_revision = 'bf5a313d0dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_group_user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('item_group_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_last_purc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('grant_avg_value', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('date_udpated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'item_group_code', 'updated_by')
    )
    op.create_index(op.f('ix_item_group_user_auth_id'), 'item_group_user_auth', ['id'], unique=False)
    op.create_index(op.f('ix_item_group_user_auth_item_group_code'), 'item_group_user_auth', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_item_group_user_auth_system_user_id'), 'item_group_user_auth', ['system_user_id'], unique=False)
    op.create_index(op.f('ix_item_group_user_auth_updated_by'), 'item_group_user_auth', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_group_user_auth_updated_by'), table_name='item_group_user_auth')
    op.drop_index(op.f('ix_item_group_user_auth_system_user_id'), table_name='item_group_user_auth')
    op.drop_index(op.f('ix_item_group_user_auth_item_group_code'), table_name='item_group_user_auth')
    op.drop_index(op.f('ix_item_group_user_auth_id'), table_name='item_group_user_auth')
    op.drop_table('item_group_user_auth')
    # ### end Alembic commands ###
