"""latest

Revision ID: 7750406b9394
Revises: de2082792541
Create Date: 2022-09-27 02:03:41.680130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '7750406b9394'
down_revision = 'de2082792541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_h', sa.Column('payment_term', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_sales_order_h_payment_method', table_name='sales_order_h')
    op.create_index(op.f('ix_sales_order_h_payment_term'), 'sales_order_h', ['payment_term'], unique=False)
    op.create_foreign_key(None, 'sales_order_h', 'payment_term', ['payment_term'], ['code'], onupdate='CASCADE')
    op.drop_column('sales_order_h', 'payment_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_h', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_order_h', type_='foreignkey')
    op.drop_index(op.f('ix_sales_order_h_payment_term'), table_name='sales_order_h')
    op.create_index('ix_sales_order_h_payment_method', 'sales_order_h', ['payment_method'], unique=False)
    op.drop_column('sales_order_h', 'payment_term')
    # ### end Alembic commands ###
