"""latest

Revision ID: 7b97de53c906
Revises: d2a7d0724685
Create Date: 2022-11-09 20:27:16.022700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '7b97de53c906'
down_revision = 'd2a7d0724685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
