"""latest

Revision ID: 82590b3fe0cd
Revises: 97c4d38a51e1
Create Date: 2022-11-04 15:11:12.030102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '82590b3fe0cd'
down_revision = '97c4d38a51e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_index('ix_customer_full_name', table_name='customer')
    op.create_index(op.f('ix_customer_card_name'), 'customer', ['card_name'], unique=False)
    op.drop_column('customer', 'full_name')
    op.drop_constraint('customer_address_customer_code_fkey', 'customer_address', type_='foreignkey')
    op.create_foreign_key(None, 'customer_address', 'customer', ['customer_code'], ['code'], ondelete='RESTRICT')
    op.drop_constraint('price_quotation_h_customer_code_fkey', 'price_quotation_h', type_='foreignkey')
    op.create_foreign_key(None, 'price_quotation_h', 'customer', ['customer_code'], ['code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_quotation_h', type_='foreignkey')
    op.create_foreign_key('price_quotation_h_customer_code_fkey', 'price_quotation_h', 'customer', ['customer_code'], ['code'], onupdate='CASCADE')
    op.drop_constraint(None, 'customer_address', type_='foreignkey')
    op.create_foreign_key('customer_address_customer_code_fkey', 'customer_address', 'customer', ['customer_code'], ['code'], onupdate='CASCADE')
    op.add_column('customer', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customer_card_name'), table_name='customer')
    op.create_index('ix_customer_full_name', 'customer', ['full_name'], unique=False)
    op.drop_column('customer', 'card_name')
    # ### end Alembic commands ###
