"""latest

Revision ID: 8c489de49fb0
Revises: 23cbe50315a1
Create Date: 2022-10-25 00:53:14.635777

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '8c489de49fb0'
down_revision = '23cbe50315a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricelist_r', sa.Column('avg_sap_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricelist_r', 'avg_sap_value')
    # ### end Alembic commands ###
