"""latest

Revision ID: 93236d7f5799
Revises: f069cae6bcac
Create Date: 2022-10-20 06:08:45.310100

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '93236d7f5799'
down_revision = 'f069cae6bcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_auth', sa.Column('update', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_sys_auth_update'), 'sys_auth', ['update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_auth_update'), table_name='sys_auth')
    op.drop_column('sys_auth', 'update')
    # ### end Alembic commands ###
