"""item_group_auth

Revision ID: 97c4d38a51e1
Revises: e3e98b9dbc21
Create Date: 2022-11-03 14:11:38.572730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '97c4d38a51e1'
down_revision = 'e3e98b9dbc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'auth_item_group', 'item_group', ['item_group_code'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_item_group', type_='foreignkey')
    # ### end Alembic commands ###
