"""latest

Revision ID: 9e97452ac26d
Revises: 467ca1e1ad11
Create Date: 2022-11-11 17:44:02.659198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = '9e97452ac26d'
down_revision = '467ca1e1ad11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_version', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_version', 'is_active')
    # ### end Alembic commands ###
