"""sales_order

Revision ID: a02e36803c70
Revises: 42b2c98b204e
Create Date: 2022-09-14 01:31:02.197381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'a02e36803c70'
down_revision = '42b2c98b204e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order_h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transdate', sa.DateTime(), nullable=True),
    sa.Column('cust_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispatching_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('docstatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('date_dispatched', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('otherfee', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_canceled', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('canceled_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['canceled_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['cust_code'], ['customer.code'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_id')
    )
    op.create_index(op.f('ix_sales_order_h_cust_code'), 'sales_order_h', ['cust_code'], unique=False)
    op.create_index(op.f('ix_sales_order_h_delivery_method'), 'sales_order_h', ['delivery_method'], unique=False)
    op.create_index(op.f('ix_sales_order_h_dispatching_branch'), 'sales_order_h', ['dispatching_branch'], unique=False)
    op.create_index(op.f('ix_sales_order_h_docstatus'), 'sales_order_h', ['docstatus'], unique=False)
    op.create_index(op.f('ix_sales_order_h_id'), 'sales_order_h', ['id'], unique=False)
    op.create_index(op.f('ix_sales_order_h_order_status'), 'sales_order_h', ['order_status'], unique=False)
    op.create_index(op.f('ix_sales_order_h_payment_method'), 'sales_order_h', ['payment_method'], unique=False)
    op.create_index(op.f('ix_sales_order_h_reference'), 'sales_order_h', ['reference'], unique=True)
    op.create_table('sales_order_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_attachment_doc_id'), 'sales_order_attachment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_sales_order_attachment_id'), 'sales_order_attachment', ['id'], unique=False)
    op.create_table('sales_order_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_user.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_comment_doc_id'), 'sales_order_comment', ['doc_id'], unique=False)
    op.create_index(op.f('ix_sales_order_comment_id'), 'sales_order_comment', ['id'], unique=False)
    op.create_table('sales_order_r',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('srp_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linetotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_order_h.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['uom.code'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_r_doc_id'), 'sales_order_r', ['doc_id'], unique=False)
    op.create_index(op.f('ix_sales_order_r_id'), 'sales_order_r', ['id'], unique=False)
    op.create_index(op.f('ix_sales_order_r_item_code'), 'sales_order_r', ['item_code'], unique=False)
    op.create_index(op.f('ix_sales_order_r_uom'), 'sales_order_r', ['uom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_r_uom'), table_name='sales_order_r')
    op.drop_index(op.f('ix_sales_order_r_item_code'), table_name='sales_order_r')
    op.drop_index(op.f('ix_sales_order_r_id'), table_name='sales_order_r')
    op.drop_index(op.f('ix_sales_order_r_doc_id'), table_name='sales_order_r')
    op.drop_table('sales_order_r')
    op.drop_index(op.f('ix_sales_order_comment_id'), table_name='sales_order_comment')
    op.drop_index(op.f('ix_sales_order_comment_doc_id'), table_name='sales_order_comment')
    op.drop_table('sales_order_comment')
    op.drop_index(op.f('ix_sales_order_attachment_id'), table_name='sales_order_attachment')
    op.drop_index(op.f('ix_sales_order_attachment_doc_id'), table_name='sales_order_attachment')
    op.drop_table('sales_order_attachment')
    op.drop_index(op.f('ix_sales_order_h_reference'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_payment_method'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_order_status'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_id'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_docstatus'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_dispatching_branch'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_delivery_method'), table_name='sales_order_h')
    op.drop_index(op.f('ix_sales_order_h_cust_code'), table_name='sales_order_h')
    op.drop_table('sales_order_h')
    # ### end Alembic commands ###
