"""latest

Revision ID: af499a810bd4
Revises: acb930b517a8
Create Date: 2022-09-26 08:47:13.215340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'af499a810bd4'
down_revision = 'acb930b517a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_address', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('customer_address', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer_address', 'brgy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer_address', 'city_municipality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_customer_address_other_details'), 'customer_address', ['other_details'], unique=False)
    op.create_index(op.f('ix_customer_address_province'), 'customer_address', ['province'], unique=False)
    op.drop_column('customer_address', 'delivery_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_address', sa.Column('delivery_fee', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_customer_address_province'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_other_details'), table_name='customer_address')
    op.alter_column('customer_address', 'city_municipality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer_address', 'brgy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer_address', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('customer_address', 'province')
    # ### end Alembic commands ###
