"""latest

Revision ID: c0de6a221503
Revises: c87ec3deb03c
Create Date: 2022-10-25 11:39:53.826584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0de6a221503'
down_revision = 'c87ec3deb03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricelist_r_logs', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricelist_r_logs', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
