"""addt'l column to itemGroup

Revision ID: c29ca5f86a8b
Revises: 1417a75c359c
Create Date: 2022-10-29 10:33:10.395912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'c29ca5f86a8b'
down_revision = '1417a75c359c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_group', sa.Column('is_allow_last_purch', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('item_group', sa.Column('is_allow_avg_value', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.create_foreign_key(None, 'price_quotation_h', 'branch', ['dispatching_branch'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_quotation_h', type_='foreignkey')
    op.drop_column('item_group', 'is_allow_avg_value')
    op.drop_column('item_group', 'is_allow_last_purch')
    # ### end Alembic commands ###
