"""latest

Revision ID: c65ccfd932dd
Revises: 68d7c515b238
Create Date: 2022-09-23 08:40:11.886503

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'c65ccfd932dd'
down_revision = '68d7c515b238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
