"""latest

Revision ID: c87ec3deb03c
Revises: a952654259e2
Create Date: 2022-10-25 11:39:04.000911

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'c87ec3deb03c'
down_revision = 'a952654259e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
