"""latest

Revision ID: c929e3e3b4c1
Revises: 23fbb5a00c57
Create Date: 2022-09-13 02:57:57.913255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'c929e3e3b4c1'
down_revision = '23fbb5a00c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_address', ['id'])
    op.add_column('system_user', sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_user', 'is_super_admin')
    op.drop_constraint(None, 'customer_address', type_='unique')
    # ### end Alembic commands ###
