"""latest

Revision ID: d7953e6ba485
Revises: e2d06e04eace
Create Date: 2022-10-11 01:14:32.656758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7953e6ba485"
down_revision = "e2d06e04eace"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
