"""latest

Revision ID: e2d06e04eace
Revises: cc2e4926924f
Create Date: 2022-10-07 06:31:40.999070

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'e2d06e04eace'
down_revision = 'cc2e4926924f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
