"""item_group_auth

Revision ID: e3e98b9dbc21
Revises: 8ceb8bcbc3f4
Create Date: 2022-11-02 10:24:29.929445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'e3e98b9dbc21'
down_revision = '8ceb8bcbc3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_item_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('item_group_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grant_last_purc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('grant_avg_value', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_user_id'], ['system_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['system_user.id'], ),
    sa.PrimaryKeyConstraint('id', 'item_group_code')
    )
    op.create_index(op.f('ix_auth_item_group_id'), 'auth_item_group', ['id'], unique=False)
    op.create_index(op.f('ix_auth_item_group_item_group_code'), 'auth_item_group', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_auth_item_group_system_user_id'), 'auth_item_group', ['system_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_item_group_system_user_id'), table_name='auth_item_group')
    op.drop_index(op.f('ix_auth_item_group_item_group_code'), table_name='auth_item_group')
    op.drop_index(op.f('ix_auth_item_group_id'), table_name='auth_item_group')
    op.drop_table('auth_item_group')
    # ### end Alembic commands ###
