"""latest

Revision ID: e80846690065
Revises: 7750406b9394
Create Date: 2022-10-05 06:32:12.505621

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'e80846690065'
down_revision = '7750406b9394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True))
    op.drop_column('customer', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('balance', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.drop_column('customer', 'credit_limit')
    # ### end Alembic commands ###
