"""latest

Revision ID: ef2ebd2767ab
Revises: 50c9dc84b0a1
Create Date: 2022-10-24 13:28:05.602212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'ef2ebd2767ab'
down_revision = '50c9dc84b0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricelist_r', sa.Column('last_purchase_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('pricelist_r', sa.Column('logistics_cost', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('pricelist_r', sa.Column('profit', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricelist_r', 'profit')
    op.drop_column('pricelist_r', 'logistics_cost')
    op.drop_column('pricelist_r', 'last_purchase_price')
    # ### end Alembic commands ###
