"""authItemGroupLogs

Revision ID: fb4c5f39fdcc
Revises: fd2491642eda
Create Date: 2022-11-07 14:51:14.978279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # new


# revision identifiers, used by Alembic.
revision = "fb4c5f39fdcc"
down_revision = "fd2491642eda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
