"""add new col

Revision ID: fd2491642eda
Revises: af58a181befb
Create Date: 2022-11-04 15:21:47.021209

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # new


# revision identifiers, used by Alembic.
revision = 'fd2491642eda'
down_revision = 'af58a181befb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('middle_initial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_customer_middle_initial'), 'customer', ['middle_initial'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_middle_initial'), table_name='customer')
    op.drop_column('customer', 'middle_initial')
    # ### end Alembic commands ###
